name: Rakujitaku
options:
  bundleIdPrefix: com.shuyafukai
  createIntermediateGroups: true

schemes:
  Rakujitaku:
    build:
      targets:
        Rakujitaku: all
        RakujitakuTests: [test]
        RakujitakuUITests: [test]
    run:
      config: Debug
      storeKitConfiguration: Rakujitaku.storekit
    test:
      config: Debug
      targets:
        - RakujitakuTests
        - RakujitakuUITests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release

targets:
  Rakujitaku:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: Rakujitaku
    info:
      path: Rakujitaku/Info.plist
      properties:
        CFBundleDisplayName: らくじたく
        CFBundleShortVersionString: "1.0.1"
        CFBundleVersion: "1"
        ITSAppUsesNonExemptEncryption: false
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UILaunchScreen:
          UIColorName: ""
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shuyafukai.rakujitaku
        MARKETING_VERSION: "1.0.1"
        CURRENT_PROJECT_VERSION: "1"
        SWIFT_VERSION: "5"
        TARGETED_DEVICE_FAMILY: "1"
        DEVELOPMENT_TEAM: B54UXU8NGQ
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor

  RakujitakuTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: RakujitakuTests
      - path: Rakujitaku.storekit
        buildPhase: resources
    dependencies:
      - target: Rakujitaku
    info:
      path: RakujitakuTests/Info.plist
      properties:
        CFBundleShortVersionString: "1.0.0"
        CFBundleVersion: "1"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shuyafukai.rakujitakutests
        SWIFT_VERSION: "5"
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/Rakujitaku.app/Rakujitaku"
        BUNDLE_LOADER: "$(TEST_HOST)"

  RakujitakuUITests:
    type: bundle.ui-testing
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: RakujitakuUITests
    dependencies:
      - target: Rakujitaku
    info:
      path: RakujitakuUITests/Info.plist
      properties:
        CFBundleShortVersionString: "1.0.0"
        CFBundleVersion: "1"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shuyafukai.rakujitakuuitests
        SWIFT_VERSION: "5"
